controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true


    wheel_brackets_cont:
      type: position_controllers/JointGroupPositionController

    rear_wheels_cont:
      type: velocity_controllers/JointGroupVelocityController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

rear_wheels_cont:
  ros__parameters:
    use_sim_time: true
    base_frame_id: base_link
    joints:
      - rear_driver_wheel_joint
      - rear_passenger_wheel_joint
    interface_name: position

wheel_brackets_cont:
  ros__parameters:
    use_sim_time: true
    base_frame_id: base_link
    joints:
      - wheel_bracket_driver_joint
      - wheel_bracket_passenger_joint
    interface_name: position